version: '3.4'

services:
  shop.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings:DefaultConnection=Server=sqlserver;Database=ShopDb;User Id=sa;Password=SajjadM;
    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro



  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SajjadM
      - MSSQL_PID=Express
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
